version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
  finance-crawler:
    build: .
    depends_on:
      - elasticsearch
      - mongo
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - .:/usr/src/app
    command: node crawler.js
