apiVersion: v1
kind: Namespace
metadata:
  name: scrapy-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: scrapy-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: scrapy-cluster
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: scrapy-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.8
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: scrapy-cluster
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapy-worker
  namespace: scrapy-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scrapy-worker
  template:
    metadata:
      labels:
        app: scrapy-worker
    spec:
      containers:
      - name: scrapy-worker
        image: scrapinghub/scrapy-cluster:latest
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: ZK_HOSTS
          value: "zookeeper:2181"
        ports:
        - containerPort: 6020
---
apiVersion: v1
kind: Service
metadata:
  name: scrapy-worker
  namespace: scrapy-cluster
spec:
  selector:
    app: scrapy-worker
  ports:
    - protocol: TCP
      port: 6020
      targetPort: 6020
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapy-manager
  namespace: scrapy-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapy-manager
  template:
    metadata:
      labels:
        app: scrapy-manager
    spec:
      containers:
      - name: scrapy-manager
        image: scrapinghub/scrapy-cluster:latest
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: ZK_HOSTS
          value: "zookeeper:2181"
        ports:
        - containerPort: 6010
---
apiVersion: v1
kind: Service
metadata:
  name: scrapy-manager
  namespace: scrapy-cluster
spec:
  selector:
    app: scrapy-manager
  ports:
    - protocol: TCP
      port: 6010
      targetPort: 6010
