apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-engine
  labels:
    app: finance-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-engine
  template:
    metadata:
      labels:
        app: finance-engine
    spec:
      containers:
      - name: finance-engine
        image: your-dockerhub-username/finance-engine:latest # Replace with your image
        ports:
        - containerPort: 8000
        env:
        - name: FINANCE_INDEX_BACKEND
          value: "elasticsearch"
        - name: ELASTIC_HOST
          value: "http://elasticsearch:9200"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: finance-engine
spec:
  selector:
    app: finance-engine
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
