version: '3.8'

services:
  finance-engine:
    build: .
    container_name: finance-engine
    ports:
      - "8081:8081"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - elasticsearch
    restart: always
    # Uncomment if you want to use GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
    restart: always
